# Generated by Django 3.2.14 on 2022-08-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dish_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'soup'), (2, 'salad'), (3, 'meat'), (4, 'fish'), (5, 'seafood'), (6, 'dessert')], null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meal_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'starter'), (2, 'main'), (3, 'dessert')], null=True),
        ),
    ]
