# Generated by Django 3.2.14 on 2022-08-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220805_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dish_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'soup'), (2, 'salad'), (3, 'bread'), (4, 'meat'), (5, 'fish'), (6, 'seafood'), (7, 'sweet'), (8, 'tangy')], null=True),
        ),
    ]
