# Generated by Django 3.2.14 on 2022-08-01 08:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dish_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'starter'), (2, 'main'), (3, 'dessert')], null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=cloudinary.models.CloudinaryField(default='yleipz1gqfmdwpnbtx0v.jpg', max_length=255, verbose_name='image'),
        ),
    ]
