# Generated by Django 3.2.14 on 2022-08-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20220801_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.PositiveSmallIntegerField(choices=[(1, '11:00-12:00'), (2, '12:00-13:00'), (3, '13:00-14:00'), (4, '14:00-15:00')], null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_people',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True),
        ),
    ]
