# Generated by Django 3.2.14 on 2022-08-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20220803_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='total_people',
            new_name='number_of_clients',
        ),
    ]
